name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven and generate reports
        run: mvn clean verify jacoco:report javadoc:javadoc spotbugs:spotbugs

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar

      - name: Upload Javadoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Move reports to docs directory
        run: |
          mkdir -p docs/jacoco
          mkdir -p docs/spotbugs
          mkdir -p docs/javadoc
          cp -r target/site/jacoco/* docs/jacoco/
          cp -r target/site/apidocs/* docs/javadoc/
          cp -r target/spotbugsXml.xml docs/spotbugs/

      - name: Generate index html
        run: |
          echo "<html><body><h1>Project Reports</h1>" > docs/index.html
          echo "<h2>JaCoCo Report</h2>" >> docs/index.html
          echo "<iframe src='jacoco/index.html' width='100%' height='600px'></iframe>" >> docs/index.html
          echo "<h2>SpotBugs Report</h2>" >> docs/index.html
          echo "<iframe src='spotbugs/spotbugsXml.xml' width='100%' height='600px'></iframe>" >> docs/index.html
          echo "<h2>Javadoc</h2>" >> docs/index.html
          echo "<iframe src='javadoc/index.html' width='100%' height='600px'></iframe>" >> docs/index.html
          echo "</body></html>" >> docs/index.html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
